sudo: required
dist: trusty
before_install:
  - wget http://131.123.42.38/lmcrs/beta/srcML-Ubuntu14.04-64.deb
  - sudo dpkg -i srcML-Ubuntu14.04-64.deb
before_script:
  - wget https://dl.bintray.com/jrfaller/cgum/cgum_latest_ubuntu_x86-64.tar.gz -O /tmp/cgum_latest_ubuntu_x86-64.tar.gz
  - tar -xvf /tmp/cgum_latest_ubuntu_x86-64.tar.gz
  - export PATH=$PATH:$PWD/cgum/
script: ./gradlew -Dgumtree.cgum.path=./cgum/cgum check
after_success:
  - ./gradlew coveralls uploadArchives
language: java
jdk:
  - oraclejdk8
deploy:
  provider: bintray
  on:
    branch: develop
  file: deploy.json
  user: jrfaller
  key:
    secure: g2h46zuZoa9GJ/lGrAePdmI7P/KhH9zImSmdERl/qlYZ2aKD9a3GuBd94v5xsTtgOoftZK4KoRfp4Wvb5IEPQPPYEjQb1ubOT/xGxyySj3wcniTAWBa2U3FLDlhU3AyPO3xn1h8HUikm7zODDXGDZxDjDvI5hxRgBiz0j/P5j7A=
